# Generated by Django 5.2.16 on 2026-07-31 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('文化艺术', '文化艺术'), ('体育竞技', '体育竞技'), ('学术科技', '学术科技'), ('公益实践', '公益实践'), ('兴趣爱好', '兴趣爱好'), ('其他', '其他')], max_length=20)),
                ('introduction', models.TextField()),
                ('logo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('normal', '正常'), ('cancelled', '已注销')], default='normal', max_length=20)),
            ],
            options={
                'db_table': 'club',
                'indexes': [models.Index(fields=['status', 'category'], name='club_status_category_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_status', models.CharField(choices=[('active', '在社'), ('exited', '已退出'), ('removed', '已移除')], default='active', max_length=20)),
                ('club_role', models.CharField(choices=[('leader', '负责人'), ('member', '普通成员')], default='member', max_length=20)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='clubs.club')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'club_membership',
                'indexes': [models.Index(fields=['club', 'member_status', 'club_role'], name='memb_club_status_role_idx'), models.Index(fields=['user', 'member_status'], name='memb_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'club'), name='unique_user_club_membership')],
            },
        ),
    ]
