# Generated by Django 5.2.16 on 2026-07-31 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('requirements', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('ended_early', models.BooleanField(default=False)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='recruitments', to='clubs.club')),
                ('publisher', models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.PROTECT, related_name='published_recruitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment',
                'indexes': [models.Index(fields=['club', 'ended_early', 'start_time', 'end_time'], name='recruit_club_early_time_idx'), models.Index(fields=['publisher'], name='recruit_publisher_idx')],
            },
        ),
    ]
