# Generated by Django 5.2.16 on 2026-07-31 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_add_recruitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applicant_name_snapshot', models.CharField(max_length=50)),
                ('applicant_major_class_snapshot', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('待审核', '待审核'), ('已通过', '已通过'), ('已拒绝', '已拒绝')], default='待审核', max_length=20)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='join_applications', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='join_applications', to='clubs.club')),
                ('recruitment', models.ForeignKey(db_column='recruitment_id', on_delete=django.db.models.deletion.PROTECT, related_name='join_applications', to='clubs.recruitment')),
            ],
            options={
                'db_table': 'join_application',
                'indexes': [models.Index(fields=['applicant', 'status'], name='ja_applicant_status_idx'), models.Index(fields=['club', 'status', 'applied_at'], name='ja_club_status_time_idx'), models.Index(fields=['recruitment', 'applicant', 'status'], name='ja_rec_app_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('有人回复了我的帖子', '有人回复了我的帖子'), ('我的举报已经处理', '我的举报已经处理'), ('我的入社申请已经审核', '我的入社申请已经审核')], max_length=50)),
                ('content', models.TextField()),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['recipient', 'type'], name='notif_recipient_type_idx')],
            },
        ),
    ]
