# Generated by Django 5.2.16 on 2026-07-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_add_join_application_and_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('正常', '正常'), ('已删除', '已删除')], default='正常', max_length=20)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='clubs.club')),
                ('publisher', models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.PROTECT, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement',
                'indexes': [models.Index(fields=['club', 'status', 'is_pinned', 'published_at'], name='ann_club_status_pin_time_idx'), models.Index(fields=['publisher'], name='ann_publisher_idx')],
            },
        ),
    ]
