# Generated by Django 5.2.16 on 2026-07-31 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_add_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('正常', '正常'), ('已删除', '已删除')], default='正常', max_length=20)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='clubs.club')),
            ],
            options={
                'db_table': 'post',
                'indexes': [models.Index(fields=['club', 'status', 'is_pinned'], name='post_club_status_pin_idx'), models.Index(fields=['author'], name='post_author_idx')],
            },
        ),
    ]
