# Generated by Django 5.2.16 on 2026-07-31 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_add_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('正常', '正常'), ('已删除', '已删除')], default='正常', max_length=20)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.PROTECT, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='clubs.post')),
            ],
            options={
                'db_table': 'reply',
                'indexes': [models.Index(fields=['post', 'status'], name='reply_post_status_idx'), models.Index(fields=['author'], name='reply_author_idx')],
            },
        ),
    ]
