# Generated by Django 5.2.16 on 2026-08-01 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_add_club_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('已处理', '已处理')], default='待处理', max_length=10)),
                ('processing_note', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='clubs.club')),
                ('submitter', models.ForeignKey(db_column='submitter_id', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['submitter'], name='fb_submitter_idx'), models.Index(fields=['club', 'status', 'submitted_at'], name='fb_club_status_time_idx')],
            },
        ),
    ]
