# Generated by Django 5.2.16 on 2026-08-01 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_add_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('已采纳', '已采纳'), ('未采纳', '未采纳')], default='待处理', max_length=20)),
                ('processing_note', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to='clubs.post')),
                ('reply', models.ForeignKey(blank=True, db_column='reply_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to='clubs.reply')),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_report',
                'indexes': [models.Index(fields=['post', 'status'], name='cr_post_status_idx'), models.Index(fields=['reply', 'status'], name='cr_reply_status_idx')],
            },
        ),
    ]
