# Generated by Django 5.2.16 on 2026-07-28 13:47

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('platform_role', models.CharField(choices=[('system_admin', '系统管理员'), ('student', '学生用户')], default='student', max_length=20)),
                ('account_status', models.CharField(choices=[('active', '正常'), ('disabled', '已停用')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('major_class', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'indexes': [models.Index(fields=['platform_role', 'account_status'], name='user_role_status_idx')],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
